// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh4xrb3aK8ExXYDb8YirMynutMCIB_lLA',
    appId: '1:978355253679:web:9869cfa5e4ec8252287f5a',
    messagingSenderId: '978355253679',
    projectId: 'log-sign-app',
    authDomain: 'log-sign-app.firebaseapp.com',
    storageBucket: 'log-sign-app.appspot.com',
    measurementId: 'G-E8RBFL2CER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrdyc-QEyc_vqcAG8FvhtmKWZqkQDKXZ4',
    appId: '1:978355253679:android:9d9efb104f0996a9287f5a',
    messagingSenderId: '978355253679',
    projectId: 'log-sign-app',
    storageBucket: 'log-sign-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW-ccloTM0xNfTTj7yd4s_cBQ7ADyLwY8',
    appId: '1:978355253679:ios:49954c72f40327bb287f5a',
    messagingSenderId: '978355253679',
    projectId: 'log-sign-app',
    storageBucket: 'log-sign-app.appspot.com',
    iosClientId: '978355253679-g130mtgnsls8o483k253ssg6vbrc89o5.apps.googleusercontent.com',
    iosBundleId: 'com.validation.logSignApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW-ccloTM0xNfTTj7yd4s_cBQ7ADyLwY8',
    appId: '1:978355253679:ios:49954c72f40327bb287f5a',
    messagingSenderId: '978355253679',
    projectId: 'log-sign-app',
    storageBucket: 'log-sign-app.appspot.com',
    iosClientId: '978355253679-g130mtgnsls8o483k253ssg6vbrc89o5.apps.googleusercontent.com',
    iosBundleId: 'com.validation.logSignApp',
  );
}
